// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/account.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AccountSignUp struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	PubK                 string   `protobuf:"bytes,2,opt,name=pub_k,json=pubK,proto3" json:"pub_k,omitempty"`
	FcmToken             string   `protobuf:"bytes,3,opt,name=fcm_token,json=fcmToken,proto3" json:"fcm_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountSignUp) Reset()         { *m = AccountSignUp{} }
func (m *AccountSignUp) String() string { return proto.CompactTextString(m) }
func (*AccountSignUp) ProtoMessage()    {}
func (*AccountSignUp) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b24b10312e6348, []int{0}
}

func (m *AccountSignUp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountSignUp.Unmarshal(m, b)
}
func (m *AccountSignUp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountSignUp.Marshal(b, m, deterministic)
}
func (m *AccountSignUp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountSignUp.Merge(m, src)
}
func (m *AccountSignUp) XXX_Size() int {
	return xxx_messageInfo_AccountSignUp.Size(m)
}
func (m *AccountSignUp) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountSignUp.DiscardUnknown(m)
}

var xxx_messageInfo_AccountSignUp proto.InternalMessageInfo

func (m *AccountSignUp) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AccountSignUp) GetPubK() string {
	if m != nil {
		return m.PubK
	}
	return ""
}

func (m *AccountSignUp) GetFcmToken() string {
	if m != nil {
		return m.FcmToken
	}
	return ""
}

func init() {
	proto.RegisterType((*AccountSignUp)(nil), "protos.AccountSignUp")
}

func init() { proto.RegisterFile("protos/account.proto", fileDescriptor_82b24b10312e6348) }

var fileDescriptor_82b24b10312e6348 = []byte{
	// 125 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0x4f, 0x4c, 0x4e, 0xce, 0x2f, 0xcd, 0x2b, 0xd1, 0x03, 0x73, 0x85, 0xd8, 0x20,
	0xa2, 0x4a, 0xb1, 0x5c, 0xbc, 0x8e, 0x10, 0x89, 0xe0, 0xcc, 0xf4, 0xbc, 0xd0, 0x02, 0x21, 0x29,
	0x2e, 0x8e, 0xd2, 0xe2, 0xd4, 0xa2, 0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce,
	0x20, 0x38, 0x5f, 0x48, 0x98, 0x8b, 0xb5, 0xa0, 0x34, 0x29, 0x3e, 0x5b, 0x82, 0x09, 0x2c, 0xc1,
	0x52, 0x50, 0x9a, 0xe4, 0x2d, 0x24, 0xcd, 0xc5, 0x99, 0x96, 0x9c, 0x1b, 0x5f, 0x92, 0x9f, 0x9d,
	0x9a, 0x27, 0xc1, 0x0c, 0xd1, 0x91, 0x96, 0x9c, 0x1b, 0x02, 0xe2, 0x27, 0x41, 0xac, 0x31, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x53, 0x53, 0x7e, 0xbe, 0x85, 0x00, 0x00, 0x00,
}
