// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/account.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageBody_Type int32

const (
	MessageBody_Text  MessageBody_Type = 0
	MessageBody_Image MessageBody_Type = 1
)

var MessageBody_Type_name = map[int32]string{
	0: "Text",
	1: "Image",
}

var MessageBody_Type_value = map[string]int32{
	"Text":  0,
	"Image": 1,
}

func (x MessageBody_Type) String() string {
	return proto.EnumName(MessageBody_Type_name, int32(x))
}

func (MessageBody_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_82b24b10312e6348, []int{4, 0}
}

type AccountSignUp struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	PubK                 string   `protobuf:"bytes,2,opt,name=pub_k,json=pubK,proto3" json:"pub_k,omitempty"`
	FcmToken             string   `protobuf:"bytes,3,opt,name=fcm_token,json=fcmToken,proto3" json:"fcm_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountSignUp) Reset()         { *m = AccountSignUp{} }
func (m *AccountSignUp) String() string { return proto.CompactTextString(m) }
func (*AccountSignUp) ProtoMessage()    {}
func (*AccountSignUp) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b24b10312e6348, []int{0}
}

func (m *AccountSignUp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountSignUp.Unmarshal(m, b)
}
func (m *AccountSignUp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountSignUp.Marshal(b, m, deterministic)
}
func (m *AccountSignUp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountSignUp.Merge(m, src)
}
func (m *AccountSignUp) XXX_Size() int {
	return xxx_messageInfo_AccountSignUp.Size(m)
}
func (m *AccountSignUp) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountSignUp.DiscardUnknown(m)
}

var xxx_messageInfo_AccountSignUp proto.InternalMessageInfo

func (m *AccountSignUp) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AccountSignUp) GetPubK() string {
	if m != nil {
		return m.PubK
	}
	return ""
}

func (m *AccountSignUp) GetFcmToken() string {
	if m != nil {
		return m.FcmToken
	}
	return ""
}

type UserModel struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	PubK                 string   `protobuf:"bytes,2,opt,name=pub_k,json=pubK,proto3" json:"pub_k,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserModel) Reset()         { *m = UserModel{} }
func (m *UserModel) String() string { return proto.CompactTextString(m) }
func (*UserModel) ProtoMessage()    {}
func (*UserModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b24b10312e6348, []int{1}
}

func (m *UserModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserModel.Unmarshal(m, b)
}
func (m *UserModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserModel.Marshal(b, m, deterministic)
}
func (m *UserModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserModel.Merge(m, src)
}
func (m *UserModel) XXX_Size() int {
	return xxx_messageInfo_UserModel.Size(m)
}
func (m *UserModel) XXX_DiscardUnknown() {
	xxx_messageInfo_UserModel.DiscardUnknown(m)
}

var xxx_messageInfo_UserModel proto.InternalMessageInfo

func (m *UserModel) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserModel) GetPubK() string {
	if m != nil {
		return m.PubK
	}
	return ""
}

type FriendRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	PubK                 string   `protobuf:"bytes,2,opt,name=pub_k,json=pubK,proto3" json:"pub_k,omitempty"`
	Timestamp            int64    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FriendRequest) Reset()         { *m = FriendRequest{} }
func (m *FriendRequest) String() string { return proto.CompactTextString(m) }
func (*FriendRequest) ProtoMessage()    {}
func (*FriendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b24b10312e6348, []int{2}
}

func (m *FriendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendRequest.Unmarshal(m, b)
}
func (m *FriendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendRequest.Marshal(b, m, deterministic)
}
func (m *FriendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendRequest.Merge(m, src)
}
func (m *FriendRequest) XXX_Size() int {
	return xxx_messageInfo_FriendRequest.Size(m)
}
func (m *FriendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FriendRequest proto.InternalMessageInfo

func (m *FriendRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *FriendRequest) GetPubK() string {
	if m != nil {
		return m.PubK
	}
	return ""
}

func (m *FriendRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Message struct {
	MessageId            int64    `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Timestamp            int64    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Deletable            bool     `protobuf:"varint,5,opt,name=deletable,proto3" json:"deletable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b24b10312e6348, []int{3}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMessageId() int64 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *Message) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Message) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Message) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Message) GetDeletable() bool {
	if m != nil {
		return m.Deletable
	}
	return false
}

type MessageBody struct {
	MessageId            int64            `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Body                 string           `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Nonce                string           `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Type                 MessageBody_Type `protobuf:"varint,4,opt,name=type,proto3,enum=protos.MessageBody_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *MessageBody) Reset()         { *m = MessageBody{} }
func (m *MessageBody) String() string { return proto.CompactTextString(m) }
func (*MessageBody) ProtoMessage()    {}
func (*MessageBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b24b10312e6348, []int{4}
}

func (m *MessageBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageBody.Unmarshal(m, b)
}
func (m *MessageBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageBody.Marshal(b, m, deterministic)
}
func (m *MessageBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageBody.Merge(m, src)
}
func (m *MessageBody) XXX_Size() int {
	return xxx_messageInfo_MessageBody.Size(m)
}
func (m *MessageBody) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageBody.DiscardUnknown(m)
}

var xxx_messageInfo_MessageBody proto.InternalMessageInfo

func (m *MessageBody) GetMessageId() int64 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *MessageBody) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *MessageBody) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *MessageBody) GetType() MessageBody_Type {
	if m != nil {
		return m.Type
	}
	return MessageBody_Text
}

type MessagesContainer struct {
	Messages             []*MessageBody `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MessagesContainer) Reset()         { *m = MessagesContainer{} }
func (m *MessagesContainer) String() string { return proto.CompactTextString(m) }
func (*MessagesContainer) ProtoMessage()    {}
func (*MessagesContainer) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b24b10312e6348, []int{5}
}

func (m *MessagesContainer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessagesContainer.Unmarshal(m, b)
}
func (m *MessagesContainer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessagesContainer.Marshal(b, m, deterministic)
}
func (m *MessagesContainer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagesContainer.Merge(m, src)
}
func (m *MessagesContainer) XXX_Size() int {
	return xxx_messageInfo_MessagesContainer.Size(m)
}
func (m *MessagesContainer) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagesContainer.DiscardUnknown(m)
}

var xxx_messageInfo_MessagesContainer proto.InternalMessageInfo

func (m *MessagesContainer) GetMessages() []*MessageBody {
	if m != nil {
		return m.Messages
	}
	return nil
}

type MessageRefresh struct {
	Messages             []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MessageRefresh) Reset()         { *m = MessageRefresh{} }
func (m *MessageRefresh) String() string { return proto.CompactTextString(m) }
func (*MessageRefresh) ProtoMessage()    {}
func (*MessageRefresh) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b24b10312e6348, []int{6}
}

func (m *MessageRefresh) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRefresh.Unmarshal(m, b)
}
func (m *MessageRefresh) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRefresh.Marshal(b, m, deterministic)
}
func (m *MessageRefresh) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRefresh.Merge(m, src)
}
func (m *MessageRefresh) XXX_Size() int {
	return xxx_messageInfo_MessageRefresh.Size(m)
}
func (m *MessageRefresh) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRefresh.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRefresh proto.InternalMessageInfo

func (m *MessageRefresh) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type AccountHandshake struct {
	Contacts             []*UserModel     `protobuf:"bytes,1,rep,name=contacts,proto3" json:"contacts,omitempty"`
	FriendRequests       []*FriendRequest `protobuf:"bytes,2,rep,name=friend_requests,json=friendRequests,proto3" json:"friend_requests,omitempty"`
	NewMessages          []*Message       `protobuf:"bytes,3,rep,name=new_messages,json=newMessages,proto3" json:"new_messages,omitempty"`
	BlockedUsers         []*UserModel     `protobuf:"bytes,4,rep,name=blocked_users,json=blockedUsers,proto3" json:"blocked_users,omitempty"`
	HasRecoveryKey       bool             `protobuf:"varint,5,opt,name=has_recovery_key,json=hasRecoveryKey,proto3" json:"has_recovery_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AccountHandshake) Reset()         { *m = AccountHandshake{} }
func (m *AccountHandshake) String() string { return proto.CompactTextString(m) }
func (*AccountHandshake) ProtoMessage()    {}
func (*AccountHandshake) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b24b10312e6348, []int{7}
}

func (m *AccountHandshake) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountHandshake.Unmarshal(m, b)
}
func (m *AccountHandshake) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountHandshake.Marshal(b, m, deterministic)
}
func (m *AccountHandshake) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountHandshake.Merge(m, src)
}
func (m *AccountHandshake) XXX_Size() int {
	return xxx_messageInfo_AccountHandshake.Size(m)
}
func (m *AccountHandshake) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountHandshake.DiscardUnknown(m)
}

var xxx_messageInfo_AccountHandshake proto.InternalMessageInfo

func (m *AccountHandshake) GetContacts() []*UserModel {
	if m != nil {
		return m.Contacts
	}
	return nil
}

func (m *AccountHandshake) GetFriendRequests() []*FriendRequest {
	if m != nil {
		return m.FriendRequests
	}
	return nil
}

func (m *AccountHandshake) GetNewMessages() []*Message {
	if m != nil {
		return m.NewMessages
	}
	return nil
}

func (m *AccountHandshake) GetBlockedUsers() []*UserModel {
	if m != nil {
		return m.BlockedUsers
	}
	return nil
}

func (m *AccountHandshake) GetHasRecoveryKey() bool {
	if m != nil {
		return m.HasRecoveryKey
	}
	return false
}

func init() {
	proto.RegisterEnum("protos.MessageBody_Type", MessageBody_Type_name, MessageBody_Type_value)
	proto.RegisterType((*AccountSignUp)(nil), "protos.AccountSignUp")
	proto.RegisterType((*UserModel)(nil), "protos.UserModel")
	proto.RegisterType((*FriendRequest)(nil), "protos.FriendRequest")
	proto.RegisterType((*Message)(nil), "protos.Message")
	proto.RegisterType((*MessageBody)(nil), "protos.MessageBody")
	proto.RegisterType((*MessagesContainer)(nil), "protos.MessagesContainer")
	proto.RegisterType((*MessageRefresh)(nil), "protos.MessageRefresh")
	proto.RegisterType((*AccountHandshake)(nil), "protos.AccountHandshake")
}

func init() { proto.RegisterFile("protos/account.proto", fileDescriptor_82b24b10312e6348) }

var fileDescriptor_82b24b10312e6348 = []byte{
	// 498 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x86, 0x71, 0xe2, 0x40, 0x7c, 0xd2, 0xa4, 0xe9, 0xb4, 0x48, 0x16, 0x05, 0x29, 0xf2, 0x2a,
	0x12, 0x90, 0x4a, 0x41, 0x62, 0x05, 0x48, 0x5c, 0x84, 0xa8, 0xaa, 0x6e, 0x86, 0x74, 0x09, 0xd6,
	0xd8, 0x3e, 0x4e, 0x2c, 0xc7, 0x33, 0x66, 0x66, 0x4c, 0xf1, 0x1b, 0xf0, 0x06, 0xac, 0x79, 0x53,
	0x64, 0x7b, 0xec, 0xa6, 0xa5, 0x48, 0x74, 0x77, 0xae, 0xff, 0xf9, 0x6c, 0xff, 0x86, 0xa3, 0x5c,
	0x0a, 0x2d, 0xd4, 0x09, 0x0b, 0x43, 0x51, 0x70, 0xbd, 0xa8, 0x53, 0x72, 0xbf, 0xa9, 0x7a, 0x5f,
	0x60, 0xfc, 0xb6, 0x69, 0x7c, 0x4e, 0xd6, 0xfc, 0x22, 0x27, 0x8f, 0x60, 0x58, 0x28, 0x94, 0x9c,
	0x65, 0xe8, 0x5a, 0x33, 0x6b, 0xee, 0xd0, 0x2e, 0x27, 0x87, 0x30, 0xc8, 0x8b, 0xc0, 0x4f, 0xdd,
	0x5e, 0xdd, 0xb0, 0xf3, 0x22, 0x38, 0x23, 0xc7, 0xe0, 0xc4, 0x61, 0xe6, 0x6b, 0x91, 0x22, 0x77,
	0xfb, 0xcd, 0x46, 0x1c, 0x66, 0xab, 0x2a, 0xf7, 0x5e, 0x81, 0x73, 0xa1, 0x50, 0x9e, 0x8b, 0x08,
	0xb7, 0x77, 0x96, 0xf6, 0xbe, 0xc2, 0xf8, 0xa3, 0x4c, 0x90, 0x47, 0x14, 0xbf, 0x15, 0xa8, 0xf4,
	0xdd, 0xe1, 0x1e, 0x83, 0xa3, 0x93, 0x0c, 0x95, 0x66, 0x59, 0x5e, 0xc3, 0xf5, 0xe9, 0x55, 0xc1,
	0xfb, 0x69, 0xc1, 0x83, 0x73, 0x54, 0x8a, 0xad, 0x91, 0x3c, 0x01, 0xc8, 0x9a, 0xd0, 0x4f, 0xa2,
	0x5a, 0xbc, 0x4f, 0x1d, 0x53, 0x39, 0x8d, 0x08, 0x01, 0x3b, 0x96, 0x22, 0x6b, 0xc5, 0xab, 0x98,
	0x4c, 0xa0, 0xa7, 0x85, 0x79, 0xe4, 0x9e, 0x16, 0xd7, 0x8f, 0xd9, 0x37, 0x8e, 0x55, 0xdd, 0x08,
	0xb7, 0xa8, 0x59, 0xb0, 0x45, 0x77, 0x30, 0xb3, 0xe6, 0x43, 0x7a, 0x55, 0xf0, 0x7e, 0x5b, 0x30,
	0x32, 0x28, 0xef, 0x44, 0x54, 0xfe, 0x07, 0x4e, 0x20, 0xa2, 0xb2, 0xc5, 0xa9, 0x62, 0x72, 0x04,
	0x03, 0x2e, 0x78, 0x88, 0x86, 0xa8, 0x49, 0xc8, 0x33, 0xb0, 0x75, 0x99, 0x63, 0xcd, 0x33, 0x59,
	0xba, 0xcd, 0xe7, 0x57, 0x8b, 0x9d, 0x5b, 0x8b, 0x55, 0x99, 0x23, 0xad, 0xa7, 0xbc, 0x63, 0xb0,
	0xab, 0x8c, 0x0c, 0xc1, 0x5e, 0xe1, 0x0f, 0x3d, 0xbd, 0x47, 0x1c, 0x18, 0x9c, 0x66, 0x6c, 0x8d,
	0x53, 0xcb, 0xfb, 0x00, 0x07, 0x66, 0x4d, 0xbd, 0x17, 0x5c, 0xb3, 0x84, 0xa3, 0x24, 0x27, 0x30,
	0x34, 0x58, 0xca, 0xb5, 0x66, 0xfd, 0xf9, 0x68, 0x79, 0x78, 0xcb, 0x0d, 0xda, 0x0d, 0x79, 0xaf,
	0x61, 0x62, 0x1a, 0x14, 0x63, 0x89, 0x6a, 0x43, 0x9e, 0xfe, 0x25, 0xb1, 0x7f, 0x43, 0x62, 0x67,
	0xfd, 0x57, 0x0f, 0xa6, 0xc6, 0xb1, 0x9f, 0x18, 0x8f, 0xd4, 0x86, 0xa5, 0x48, 0x9e, 0xc3, 0x30,
	0xac, 0x88, 0x42, 0xdd, 0x2a, 0x1c, 0xb4, 0x0a, 0x9d, 0xfd, 0x68, 0x37, 0x42, 0xde, 0xc0, 0x7e,
	0x5c, 0xfb, 0xca, 0x97, 0x8d, 0xb1, 0x94, 0xdb, 0xab, 0xb7, 0x1e, 0xb6, 0x5b, 0xd7, 0x6c, 0x47,
	0x27, 0xf1, 0x6e, 0xaa, 0xc8, 0x12, 0xf6, 0x38, 0x5e, 0xfa, 0x1d, 0x74, 0xff, 0x76, 0xe8, 0x11,
	0xc7, 0xcb, 0xf6, 0x85, 0x91, 0x97, 0x30, 0x0e, 0xb6, 0x22, 0x4c, 0x31, 0xf2, 0x2b, 0xcb, 0x2a,
	0xd7, 0xfe, 0x17, 0xe7, 0x9e, 0x99, 0xab, 0x2a, 0x8a, 0xcc, 0x61, 0xba, 0x61, 0xca, 0x97, 0x18,
	0x8a, 0xef, 0x28, 0x4b, 0x3f, 0xc5, 0xd2, 0xb8, 0x67, 0xb2, 0x61, 0x8a, 0x9a, 0xf2, 0x19, 0x96,
	0x41, 0xf3, 0x4b, 0xbf, 0xf8, 0x13, 0x00, 0x00, 0xff, 0xff, 0xa2, 0xc7, 0xb6, 0xf5, 0xf1, 0x03,
	0x00, 0x00,
}
