// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/communication.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ServerResponse_Status int32

const (
	ServerResponse_Ok    ServerResponse_Status = 0
	ServerResponse_ERROR ServerResponse_Status = 1
)

var ServerResponse_Status_name = map[int32]string{
	0: "Ok",
	1: "ERROR",
}

var ServerResponse_Status_value = map[string]int32{
	"Ok":    0,
	"ERROR": 1,
}

func (x ServerResponse_Status) String() string {
	return proto.EnumName(ServerResponse_Status_name, int32(x))
}

func (ServerResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a9db6ee45f90bde9, []int{0, 0}
}

type ServerResponse struct {
	Status               ServerResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=protos.ServerResponse_Status" json:"status,omitempty"`
	StatusCode           int32                 `protobuf:"varint,2,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message              string                `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ServerResponse) Reset()         { *m = ServerResponse{} }
func (m *ServerResponse) String() string { return proto.CompactTextString(m) }
func (*ServerResponse) ProtoMessage()    {}
func (*ServerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9db6ee45f90bde9, []int{0}
}

func (m *ServerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerResponse.Unmarshal(m, b)
}
func (m *ServerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerResponse.Marshal(b, m, deterministic)
}
func (m *ServerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerResponse.Merge(m, src)
}
func (m *ServerResponse) XXX_Size() int {
	return xxx_messageInfo_ServerResponse.Size(m)
}
func (m *ServerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServerResponse proto.InternalMessageInfo

func (m *ServerResponse) GetStatus() ServerResponse_Status {
	if m != nil {
		return m.Status
	}
	return ServerResponse_Ok
}

func (m *ServerResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *ServerResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("protos.ServerResponse_Status", ServerResponse_Status_name, ServerResponse_Status_value)
	proto.RegisterType((*ServerResponse)(nil), "protos.ServerResponse")
}

func init() { proto.RegisterFile("protos/communication.proto", fileDescriptor_a9db6ee45f90bde9) }

var fileDescriptor_a9db6ee45f90bde9 = []byte{
	// 171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0x4f, 0xce, 0xcf, 0xcd, 0x2d, 0xcd, 0xcb, 0x4c, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf,
	0xd3, 0x03, 0x0b, 0x0a, 0xb1, 0x41, 0xe4, 0x94, 0xe6, 0x31, 0x72, 0xf1, 0x05, 0xa7, 0x16, 0x95,
	0xa5, 0x16, 0x05, 0xa5, 0x16, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x99, 0x72, 0xb1, 0x15, 0x97,
	0x24, 0x96, 0x94, 0x16, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x19, 0xc9, 0x42, 0xb4, 0x14, 0xeb,
	0xa1, 0xaa, 0xd3, 0x0b, 0x06, 0x2b, 0x0a, 0x82, 0x2a, 0x16, 0x92, 0xe3, 0xe2, 0x82, 0xb0, 0x9c,
	0xf3, 0x53, 0x52, 0x25, 0x98, 0x14, 0x18, 0x35, 0x58, 0x83, 0x90, 0x44, 0x84, 0x24, 0xb8, 0xd8,
	0x73, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x25, 0x98, 0x15, 0x18, 0x35, 0x38, 0x83, 0x60, 0x5c,
	0x25, 0x69, 0x2e, 0x36, 0x88, 0x59, 0x42, 0x6c, 0x5c, 0x4c, 0xfe, 0xd9, 0x02, 0x0c, 0x42, 0x9c,
	0x5c, 0xac, 0xae, 0x41, 0x41, 0xfe, 0x41, 0x02, 0x8c, 0x49, 0x10, 0x87, 0x1a, 0x03, 0x02, 0x00,
	0x00, 0xff, 0xff, 0xd8, 0xde, 0x8e, 0xef, 0xcd, 0x00, 0x00, 0x00,
}
